name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Copy files to EC2 and deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            set -e

            # ensure the deploy directory exists and is owned by the user
            DEPLOY_DIR="/home/${{ secrets.EC2_USER }}/myapp"
            if [ ! -d "$DEPLOY_DIR" ]; then
              mkdir -p "$DEPLOY_DIR"
              chown ${{ secrets.EC2_USER }}:$${{ secrets.EC2_USER }} "$DEPLOY_DIR" || true
            fi

            # clone if not present, otherwise pull latest
            if [ ! -d "$DEPLOY_DIR/.git" ]; then
              git clone https://github.com/${{ github.repository }} "$DEPLOY_DIR"
            else
              cd "$DEPLOY_DIR"
              git fetch --all
              git reset --hard origin/main
            fi

            cd "$DEPLOY_DIR"

            # For static site (index.html) — copy to webroot using sudo
            sudo cp -f index.html /var/www/html/index.html
            sudo chown www-data:www-data /var/www/html/index.html || true
            sudo chmod 644 /var/www/html/index.html || true

            # If you have other static assets:
            # sudo cp -r ./assets /var/www/html/

            # OR for Node.js app (uncomment if needed):
            # npm ci
            # pm2 restart all || pm2 start app.js --name myapp

            echo "Deployment successful!"

      - name: Notify on Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

